<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_naranja@4x.png?raw=true" alt="esquema" />
</div>

# Laboratorio Filtrado de Datos

En este laboratorio usaremos el DataFrame creado en la lección anterior resultado de la unión de los conjuntos de datos compartidos contigo. 

**Instrucciones:**

1. Lee cuidadosamente el enunciado de cada ejercicio.

2. Implementa la solución en la celda de código proporcionada.

In [142]:
def filtro_pandas_str(dataframe,columna_a_filtrar,patron_regex):
    return dataframe[columna_a_filtrar].str.contains(patron_regex, case = False, na = True)

In [120]:
import pandas as pd
import numpy as np

In [ ]:
# Carga el dataset de trabajo
df = pd.read_csv("../../labs/lab2_m2_pandas/datos/netflix_mergeado.csv",index_col=0)
df.head(5)

#### Ejercicio 1: ¿Cuáles son todos los títulos lanzados en 2021 que son del tipo 'Movie'?

In [ ]:
df["release_year"].dtypes

In [ ]:
condicion_movie = df["type"] == "Movie"
condicion_2021 = df["release_year"] == 2021

df[condicion_movie & condicion_2021]

#### Ejercicio 2: ¿Qué títulos tienen una duración de 90 minutos? Muestra solo las columnas de título y de duración.

In [ ]:
df.loc[df["duration"] == "90 min",["title", "duration","director"]].head(5)

#### Ejercicio 3: ¿Cuáles son todos los títulos del país 'India' lanzados después de 2018?

In [ ]:
condicion_india = df["country"] == "India"
condicionmasque2018 = df["release_year"] > 2018

df[condicion_india & condicionmasque2018][["title","country"]].reset_index()

#### Ejercicio 4: ¿Qué títulos tienen clasificación 'TV-14' o 'R'?

In [ ]:
clasificacion_TV14 = df["rating"] == "TV-14"
clasificacion_R = df["rating"] == "R"

df[clasificacion_R | clasificacion_TV14]["title"]

#### Ejercicio 5: ¿Cuáles son los títulos dirigidos por 'Christopher Nolan' o 'Martin Scorsese'? ¿Cuántos ha dirigido cada uno de los directores?

In [ ]:
#Filtrado para encontrar a Christopher Nolan (No está)
patron_regex = r"^c"
filtro_ = df["director"].str.contains(patron_regex, case = False, na = True)
df_filtrado = df[filtro_]
df_filtrado.sort_values(by = "director").value_counts()

In [ ]:
lista_directores = ["Christopher Nolan", "Martin Scorsese"]

df[df["director"].isin(lista_directores)]

#### Ejercicio 6: ¿Qué títulos pertenecen a los países 'United States', 'United Kingdom' o 'Canada'? Dentro de estos países, ¿cuántas películas tienen más de un lenguaje?

In [ ]:
df[df["country"] == "United Kingdom"]

In [278]:

lista_paises = ["United States","United Kingdom","Canada"]
df_paises = df[df["country"].isin(lista_paises)]

In [283]:
patron_regex = r"/"
filtro = df_paises["Language"].str.contains(patron_regex, case= False)

C:\Users\Víctor\AppData\Local\Temp\ipykernel_14468\54529642.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df[filtro]

IndexingError: Unalignable boolean Series provided as indexer (index of the boolean Series and of the indexed object do not match).

#### Ejercicio 7: ¿Qué títulos fueron lanzados entre 2015 y 2020, inclusive?

In [147]:
condicion_fechas = df["release_year"].between(2015,2020, inclusive = "both")
df[condicion_fechas].head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead,Documentary,"October 2, 2020",90,7.5,English
1,s142,Movie,Extraction,Steven C. Miller,"Bruce Willis, Kellan Lutz, Gina Carano, D.B. S...","United States, United Kingdom, Canada","September 1, 2021",2015,R,82 min,Action & Adventure,"When a retired CIA agent is kidnapped, his son...",Extraction,Action,"April 24, 2020",117,6.7,English
42,s1324,Movie,Layla Majnun,Monty Tiwa,"Reza Rahadian, Acha Septriasa, Baim Wong, Beby...",Indonesia,"February 11, 2021",2020,TV-14,119 min,"Dramas, International Movies, Romantic Movies","While in Azerbaijan, Layla, an Indonesian scho...",Layla Majnun,Romantic drama,"February 11, 2021",119,6.4,Indonesian
49,s1345,Movie,The Last Paradiso,Rocco Ricciardulli,"Riccardo Scamarcio, Gaia Bermani Amaral, Valen...",Italy,"February 5, 2021",2020,TV-MA,107 min,"Dramas, International Movies, Romantic Movies","In 1950s Italy, a passionate free spirit dream...",The Last Paradiso,Romantic drama,"February 5, 2021",107,5.6,Italian
54,s1404,Movie,Double Dad,Cris D'Amato,"Maisa Silva, Eduardo Moscovis, Marcelo Médici,...",Brazil,"January 15, 2021",2020,TV-G,NaN,"Children & Family Movies, Comedies, Dramas","While her mom is away, a teen sneaks out of th...",Double Dad,Comedy-drama,"January 15, 2021",103,5.6,Portuguese

#### Ejercicio 8: ¿Cuáles son los títulos cuya puntuación en IMDb está entre 6.5 y 8.0 y que no sepamos cual es su duración?

In [149]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'Title', 'Genre', 'Premiere', 'Runtime', 'IMDB Score', 'Language'],
      dtype='object')

In [156]:
condicion_IMDB = df["IMDB Score"].between(6.5,8.0, inclusive = "both")
condicion_duracion = df["duration"].isnull == True 
df[condicion_duracion & condicion_IMDB]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, Title, Genre, Premiere, Runtime, IMDB Score, Language]
Index: []

#### Ejercicio 9: ¿Cuáles son las películas cuya duración de 90 y 150 minutos?

In [186]:
condicion_duracion = ["90 min","150 min"]
df[df["duration"].isin(condicion_duracion)].head(3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language,Mins,unidad
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead,Documentary,"October 2, 2020",90,7.5,English,90 min,None
33,s1172,Movie,Seaspiracy,Ali Tabrizi,NaN,United States,"March 24, 2021",2021,TV-14,90 min,Documentaries,"Passionate about ocean life, a filmmaker sets ...",Seaspiracy,Documentary,"March 24, 2021",89,8.2,English,90 min,None
52,s1373,Movie,June & Kopi,Noviandra Santosa,"Acha Septriasa, Ryan Delon, Makayla Rose Hilli...",Indonesia,"January 28, 2021",2021,TV-PG,90 min,"Children & Family Movies, Dramas, Internationa...","A street dog is taken in by a young couple, an...",June & Kopi,Drama,"January 28, 2021",90,6.3,Indonesian,90 min,None

#### Ejercicio 10: ¿Cuáles son los títulos que contienen la palabra 'Love' en su título y que sean de tipo TV Show?

In [274]:
patron_regex = r"love"
condicion_titulo = df["title"].str.contains(patron_regex, case = False)
condicion_tipo = df["type"] == "TV show"

df[condicion_titulo & condicion_tipo]["title"]

Series([], Name: title, dtype: object)

#### Ejercicio 11: ¿Cuáles son los títulos en los que el director tiene el apellido 'Johnson'?

In [203]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'Title', 'Genre', 'Premiere', 'Runtime', 'IMDB Score', 'Language',
       'Mins', 'unidad'],
      dtype='object')

#### Ejercicio 12: ¿Tenemos algún documental ('Documentaries') de Mike Tyson?

In [207]:
condicion_tipo = df["listed_in"] == "Documentaries"
patron_regex = r"mike tyson"
condicion_mike = df["cast"].str.contains(patron_regex, case=False,na=False)

df[condicion_tipo & condicion_mike][["title","listed_in","cast"]]

Empty DataFrame
Columns: [title, listed_in, cast]
Index: []

#### Ejercicio 13: Selecciona solo las columnas 'title', 'country' y 'release_year' del dataset.

In [202]:
df[['title', 'country', 'release_year']]

,title,country,release_year
0,Dick Johnson Is Dead,United States,2020
1,Extraction,"United States, United Kingdom, Canada",2015
2,Prime Time,NaN,2021
3,Blue Miracle,United States,2021
4,Ghost Lab,Thailand,2021
...,...,...,...
508,Tig,United States,2015
509,"What Happened, Miss Simone?",United States,2015
510,Hot Girls Wanted,United States,2015
511,The Other One: The Long Strange Trip of Bob Weir,United States,2015
512,My Own Man,United States,2015

#### Ejercicio 14: Filtra las columnas que contienen la palabra 'date'.

In [220]:
df.filter(like = "date")

             date_added
0    September 25, 2021
1     September 1, 2021
2         June 30, 2021
3          May 27, 2021
4          May 27, 2021
..                  ...
508       July 17, 2015
509       June 26, 2015
510        May 29, 2015
511        May 22, 2015
512       March 6, 2015

[513 rows x 1 columns]

#### Ejercicio 15: Usando `query()`, filtra todos los títulos del país 'France' con una duración de 80 minutos.

In [240]:
df_filtrado = df.query('country == "France" and duration == "80 min"')
df_filtrado

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, Title, Genre, Premiere, Runtime, IMDB Score, Language, Mins, unidad]
Index: []

#### Ejercicio 16: Filtra los títulos que son películas ('Movie') y fueron lanzados antes de 2010.

In [251]:
df_filtrado_16 = df.query('type == "Movie" and "release_year" < "2010"')
df_filtrado_16

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, Title, Genre, Premiere, Runtime, IMDB Score, Language, Mins, unidad]
Index: []

#### Ejercicio 17: Encuentra los 10 títulos con las puntuaciones más altas en IMDb.

In [252]:
df.nlargest(10,"IMDB Score").filter(["title"])

                                           title
118     David Attenborough: A Life on Our Planet
336                      Springsteen on Broadway
506  Winter on Fire: Ukraine's Fight for Freedom
255                       Dancing with the Birds
421                       Cuba and the Cameraman
33                                    Seaspiracy
114        The Three Deaths of Marisela Escobedo
243                                        Klaus
136                           My Octopus Teacher
142                               Rising Phoenix

#### Ejercicio 18: Encuentra los 5 títulos con las puntuaciones más bajas en IMDb.

In [253]:
df.nsmallest(10,"IMDB Score").filter(["title"])

                               title
281                  Enter the Anime
144                      Dark Forces
228                          The App
416                   The Open House
99                       Kaali Khuhi
246                            Drive
77                 Leyla Everlasting
181  The Last Days of American Crime
403                          Paradox
8                 Sardar Ka Grandson

#### Ejercicio 19: Filtra todos los títulos que no tienen un director asignado (valores nulos en la columna 'director').

In [258]:
mask = df["director"].isnull()
df[mask]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language,Mins,unidad
24,s1093,Movie,Dolly Parton: A MusiCares Tribute,NaN,Dolly Parton,NaN,"April 7, 2021",2021,TV-PG,55 min,"Documentaries, Music & Musicals",In a star-studded evening of music and memorie...,Dolly Parton: A MusiCares Tribute,Documentary,"April 7, 2021",55,6.5,English,55 min,None
30,s1158,Movie,Bad Trip,NaN,"Eric André, Lil Rel Howery, Tiffany Haddish, M...",United States,"March 26, 2021",2021,TV-MA,NaN,Comedies,"In this hidden-camera prank comedy, two best f...",Bad Trip,Hidden-camera prank comedy,"March 26, 2021",86,6.6,English,NaN,None
59,s1432,Movie,Stuck Apart,NaN,"Engin Günaydın, Haluk Bilginer, Binnur Kaya, Ö...",Turkey,"January 8, 2021",2021,TV-MA,NaN,"Comedies, Dramas, International Movies","Entrenched in a midlife crisis, Aziz seeks sol...",Stuck Apart,Drama,"January 8, 2021",96,6.1,Turkish,NaN,None
62,s1467,Movie,The Minimalists: Less Is Now,NaN,NaN,United States,"January 1, 2021",2021,TV-14,54 min,Documentaries,They've built a movement out of minimalism. Lo...,The Minimalists: Less Is Now,Documentary,"January 1, 2021",53,5.9,English,54 min,None
70,s1519,Movie,Ma Rainey's Black Bottom: A Legacy Brought to ...,NaN,"Glynn Turman, Denzel Washington, George C. Wol...",NaN,"December 18, 2020",2020,TV-PG,32 min,"Documentaries, Music & Musicals","Viola Davis, Denzel Washington, George C. Wolf...",Ma Rainey's Black Bottom: A Legacy Brought to ...,Aftershow / Interview,"December 18, 2020",31,7.0,English,32 min,None
77,s1595,Movie,Leyla Everlasting,NaN,"Demet Akbağ, Haluk Bilginer, Elçin Sangu, Fıra...",Turkey,"December 4, 2020",2020,TV-MA,113 min,"Comedies, International Movies","A resilient housewife, her husband and their m...",Leyla Everlasting,Comedy,"December 4, 2020",112,3.7,Turkish,113 min,None
126,s1933,Movie,The Boys in the Band: Something Personal,NaN,"Jim Parsons, Zachary Quinto, Matt Bomer, Andre...",United States,"September 30, 2020",2020,TV-MA,28 min,"Documentaries, LGBTQ Movies",Decades after his play first put gay life cent...,The Boys in the Band: Something Personal,Aftershow / Interview,"September 30, 2020",28,6.8,English,28 min,None
142,s2098,Movie,Rising Phoenix,NaN,NaN,United Kingdom,"August 26, 2020",2020,PG-13,107 min,"Documentaries, International Movies, Sports Mo...",Elite athletes and insiders reflect on the Par...,Rising Phoenix,Documentary,"August 26, 2020",106,8.1,English,107 min,None
146,s2110,Movie,John Was Trying to Contact Aliens,NaN,NaN,United States,"August 20, 2020",2020,TV-PG,17 min,"Documentaries, LGBTQ Movies",A rural electronics whiz broadcasts radio sign...,John Was Trying to Contact Aliens,Documentary,"August 20, 2020",16,6.4,English,17 min,None
194,s2609,Movie,Murder to Mercy: The Cyntoia Brown Story,NaN,NaN,United States,"April 29, 2020",2020,TV-MA,NaN,Documentaries,After 16-year-old Cyntoia Brown is sentenced t...,Murder to Mercy: The Cyntoia Brown Story,Documentary,"April 29, 2020",97,6.4,English,NaN,None
201,s2693,Movie,LA Originals,NaN,NaN,"United States, Argentina","April 10, 2020",2020,TV-MA,NaN,"Documentaries, International Movies, Music & M...",Photographer Estevan Oriol and artist Mister C...,LA Originals,Documentary,"April 10, 2020",92,7.2,English,NaN,None
210,s2780,Movie,Crip Camp: A Disability Revolution,NaN,NaN,United States,"March 25, 2020",2020,R,NaN,Documentaries,A groundbreaking summer camp galvanizes a grou...,Crip Camp: A Disability Revolution,Documentary,"March 25, 2020",108,7.7,English,NaN,None
234,s3182,Movie,The Irishman: In Conversation,NaN,"Martin Scorsese, Robert De Niro, Al Pacino, Jo...",United States,"December 5, 2019",2019,TV-MA,NaN,Documentaries,Join director Martin Scorsese as he sits down ...,The Irishman: In Conversation,Aftershow / Interview,"November 27, 2019",23,7.4,English,NaN,None
273,s3536,Movie,American Factory: A Conversation with the Obamas,NaN,"President Barack Obama, Michelle Obama, Julia ...",United States,"September 5, 2019",2019,TV-G,10 min,Documentaries,Barack and Michelle Obama talk with directors ...,American Factory: A Conversation with the Obamas,Aftershow / Interview,"August 21, 2019",10,5.2,English,10 min,None
278,s3581,Movie,Invader Zim: Enter the Florpus,NaN,"Richard Steven Horvitz, Rikki Simons, Andy Ber...","South Korea, United States","August 16, 2019",2019,TV-Y7,NaN,"Children & Family Movies, Comedies, Sci-Fi & F...",When Zim reappears to begin the next phase of ...,Invader Zim: Enter the Florpus,Animation / Science Fiction,"August 16, 2019",71,7.5,English,NaN,None
282,s3630,Movie,Otherhood,NaN,NaN,"United Kingdom, United States","August 2, 2019",2019,R,NaN,Comedies,"Feeling forgotten on Mother's Day, three best ...",Otherhood,Comedy,"August 2, 2019",100,6.1,English,NaN,None
316,s3988,Movie,Antoine Griezmann: The Making of a Legend,NaN,NaN,NaN,"March 21, 2019",2019,TV-PG,60 min,"Documentaries, International Movies, Sports Mo...","With heart and determination, Antoine Griezman...",Antoine Griezmann: The Making of a Legend,Documentary,"March 21, 2019",60,6.5,French,60 min,None
329,s4171,Movie,Polar,NaN,NaN,"United States, Germany","January 25, 2019",2019,TV-MA,119 min,"Action & Adventure, International Movies",An assassin on the verge of retirement must pu...,Polar,Action,"January 25, 2019",118,6.3,English,119 min,None
348,s4387,Movie,The Princess Switch,NaN,"Vanessa Hudgens, Sam Palladio, Nick Sagar, Sua...",United States,"November 16, 2018",2018,TV-G,NaN,"Children & Family Movies, Dramas, Romantic Movies",When a down-to-earth Chicago baker and a soon-...,The Princess Switch,Romantic comedy,"November 16, 2018",101,6.0,English,NaN,None
355,s4492,Movie,Derren Brown: Sacrifice,NaN,Derren Brown,NaN,"October 19, 2018",2018,TV-MA,50 min,Movies,Illusionist Derren Brown concocts a psychologi...,Derren Brown: Sacrifice,Mentalism special,"October 19, 2018",49,7.1,English,50 min,None
366,s4645,Movie,Reversing Roe,NaN,"Ricki Stern, Annie Sundberg",United States,"September 13, 2018",2018,TV-14,NaN,Documentaries,Through interviews with abortion rights suppor...,Reversing Roe,Documentary,"September 13, 2018",99,7.5,English,NaN,None
376,s4762,Movie,Father of the Year,NaN,"David Spade, Nat Faxon, Joey Bragg, Matt Shive...",United States,"July 20, 2018",2018,TV-MA,NaN,Comedies,A drunken debate between two recent college gr...,Father of the Year,Comedy,"July 20, 2018",94,5.2,English,NaN,None

#### Ejercicio 20: Filtra todos los títulos que tienen información completa en las columnas 'title', 'country' y 'IMDB Score'.

In [226]:
    f1 = df["title"].notna()
    f2 =df["country"].notna()
    f3 = df["IMDB Score"].notna()

    df[f1 & f2 & f3]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,Title,Genre,Premiere,Runtime,IMDB Score,Language,Mins,unidad
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",Dick Johnson Is Dead,Documentary,"October 2, 2020",90,7.5,English,90 min,None
1,s142,Movie,Extraction,Steven C. Miller,"Bruce Willis, Kellan Lutz, Gina Carano, D.B. S...","United States, United Kingdom, Canada","September 1, 2021",2015,R,82 min,Action & Adventure,"When a retired CIA agent is kidnapped, his son...",Extraction,Action,"April 24, 2020",117,6.7,English,82 min,None
3,s835,Movie,Blue Miracle,Julio Quintana,"Jimmy Gonzales, Dennis Quaid, Anthony Gonzalez...",United States,"May 27, 2021",2021,TV-PG,NaN,"Children & Family Movies, Dramas, Faith & Spir...","To save their cash-strapped orphanage, a guard...",Blue Miracle,Drama,"May 27, 2021",95,6.7,English,NaN,None
4,s837,Movie,Ghost Lab,Paween Purijitpanya,"Thanapob Leeratanakachorn, Paris Intarakomalya...",Thailand,"May 27, 2021",2021,TV-MA,118 min,"Horror Movies, International Movies, Thrillers","After witnessing a haunting in their hospital,...",Ghost Lab,Horror,"May 26, 2021",117,5.2,Thai,118 min,None
5,s841,Movie,Baggio: The Divine Ponytail,Letizia Lamartire,"Andrea Arcangeli, Valentina Bellè, Andrea Penn...",Italy,"May 26, 2021",2021,TV-MA,NaN,"Dramas, International Movies, Sports Movies","The story of Roberto Baggio, one of the best s...",Baggio: The Divine Ponytail,Biopic,"May 26, 2021",92,6.2,Italian,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
508,s5902,Movie,Tig,"Kristina Goolsby, Ashley York",Tig Notaro,United States,"July 17, 2015",2015,TV-14,NaN,"Documentaries, Stand-Up Comedy",Comedian Tig Notaro announced her cancer diagn...,Tig,Documentary,"July 17, 2015",80,7.4,English,NaN,None
509,s5907,Movie,"What Happened, Miss Simone?",Liz Garbus,NaN,United States,"June 26, 2015",2015,TV-14,NaN,"Documentaries, Music & Musicals","Using never-before-heard recordings, rare arch...","What Happened, Miss Simone?",Documentary,"June 26, 2015",84,7.6,English,NaN,None
510,s5911,Movie,Hot Girls Wanted,"Jill Bauer, Ronna Gradus",NaN,United States,"May 29, 2015",2015,TV-MA,83 min,Documentaries,This 2015 Sundance Film Festival breakout docu...,Hot Girls Wanted,Documentary,"May 29, 2015",84,6.1,English,83 min,None
511,s5913,Movie,The Other One: The Long Strange Trip of Bob Weir,Mike Fleiss,Bob Weir,United States,"May 22, 2015",2015,TV-14,84 min,"Documentaries, Music & Musicals",This chronicle of Bob Weir highlights his brot...,The Other One: The Long Strange Trip of Bob Weir,Documentary,"May 22, 2015",83,7.3,English,84 min,None
512,s5917,Movie,My Own Man,David Sampliner,David Sampliner,United States,"March 6, 2015",2015,TV-MA,82 min,Documentaries,When a man discovers he will be the father to ...,My Own Man,Documentary,"December 13, 2014",81,6.4,English,82 min,None

#### Ejercicio 21: Identifica si hay títulos duplicados en la columna 'title'.

In [261]:
dupla = df["title"].duplicated()
df[dupla]

Empty DataFrame
Columns: [show_id, type, title, director, cast, country, date_added, release_year, rating, duration, listed_in, description, Title, Genre, Premiere, Runtime, IMDB Score, Language, Mins, unidad]
Index: []